### ISSUE TITLE
LMS 크롤링 전 로그인 구현

### ISSUE THREAD

**Issue by ByteAurora** [ILoveGameCoding/LMS-Reminder#1]
# LMS 크롤링 전 로그인 구현
> LMS 내 사용자의 과제현황 등을 크롤링하기 로그인 처리가 먼저 이루어져야 함

<br>

## 문제
> POST 후 반환된 RESPONSE에서 Cookie를 가져와 다음 REQUEST 헤더에 Cookie를 넣어서 전송 -> 로그인 이전의 html 페이지만 반환
> 
>**POST 로 반환된 RESPONSE의 BODY값도 로그인 이전의 LMS 페이지로 확인**

<br>

## 테스트<br>
> **1. REDIRECT 동작여부**
>    - FLUTTER HTTP의 REDIRECT값은 기본값이 TRUE
> <br>
>
> **2. LMS 사이트 문제**
>    - [POSTMAN](https://www.postman.com/)과 PYTHON으로 테스트해본 결과 동작 잘됨
> <br>
>
> **3. ANDROID 내 네트워크 문제(보안, 권한 등)**
>    - 순수 dart로만 돌려봤는데 dart에서도 작동되지 않음

<br>

## 테스트용 dart 코드
<pre><code>Future httpPostTest(String username, String password) async {
  Map<String, String> headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive'
  };

  Map<String, String> body = {'username': username, 'password': password};

  final http.Response response = await http.post(
      Uri.parse('https://learn.hoseo.ac.kr/login/index.php'),
      headers: headers,
      body: body);

  print(response.body.contains('예정'));
}</code></pre>

<br><br>

**관련 질문이나 문제 해결하면 Comment 남겨주세용**

**Comment by ByteAurora** [comment]
참고로 테스트 코드 실행하려면 http 패키지 추가해야됨

**pubspec.yaml 내 dependencies에 http 패키지 추가**

<pre><code>...
dependencies:
   http: ^0.13.0
...</code></pre>

**Comment by Blenbre777** [comment]
<h1>신기행

**Comment by ByteAurora** [comment]
테스트용 전체 코드

<pre><code>import 'dart:convert';
import 'dart:io';
import 'package:dio/dio.dart';

import 'package:http/http.dart' as http;

void main(List<String> arguments) {
  httpPostTest('https://learn.hoseo.ac.kr/login/index.php', '학번입력', '비밀번호입력');
}

Future httpPostTest(String url, String username, String password) async {
  Map<String, String> body = {'username': username, 'password': password};

  Map<String, String> headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Accept': 'text/html; charset=utf-8',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
  };

  http.Response response =
      await http.post(Uri.parse(url), body: body, headers: headers);

  print(response.body.contains('예정'));
}</code></pre>

**Comment by ByteAurora** [comment]
1. Chrome 개발자 도구로 확인한 Request의 헤더들 직접 추가 (안됨)
    - 참고: https://rongscodinghistory.tistory.com/46
2. Redirect 상태 확인
    - 참고: https://stackoverflow.com/questions/62012502/how-to-post-x-www-form-urlencoded-in-flutter
    - follow(allow) redirect = false로 해서 확인한 결과 python, dart 모두 status code는 303이지만, dart의 경우 아이디 비밀번호 일치 여부에 상관없이 location 주소가 'https://learn.hoseo.ac.kr/login.php'로 고정, python의 경우에는 아이디 비밀번호 일치 시 'https://learn.hoseo.ac.kr/', 불일치 시 'https://learn.hoseo.ac.kr/login.php?errorcode=3'가 표시

**Comment by seo0jjjjj** [comment]
# ISSUE 해결 
> 
>  ## 기존문제
> 1. POST 후 반환된 RESPONSE에서 Cookie를 가져와 다음 REQUEST 헤더에 Cookie:cookie:를 넣어서 전송 -> 로그인 이전의 html 페이지만 반환
> 2. POST 로 반환된 RESPONSE의 BODY값도 로그인 이전의 LMS 페이지로 확인
> 
> ## 문제원인
>    *  dio의 POST 요청은 웹브라우저의 로그인 과정과 다름. 

<table border=1>
<tr>
<th>웹브라우저 로그인 과정 </th><th>dio의 POST 요청 과정</th>
</tr>
<tr>
<td>
1. 아이디와 비밀번호 입력 :white_check_mark: <br>
2. 로그인 성공! 세션쿠키 반환 :white_check_mark: <br>
3. :tada: 세션쿠키를 유지하며 learn.hoseo.edu 로 이동. :tada: <br>
</td>
<td>
1. 아이디와 비밀번호를 body에 넣어 post 요청 전송.  :white_check_mark:<br>
2. 로그인 성공! 세션쿠키 반환 :white_check_mark: <br>
3. learn.hoseo.edu/login/index.php로 이동 :open_mouth::open_mouth: <br>
4. /login.php로 이동 :scream::scream:<br>
5. /login.php 반환 :bomb::bomb::bomb: 
</td>

</table>


>> ## Redirect 상세 Debug 화면
>> ![image](https://user-images.githubusercontent.com/54611807/168311376-ff7f5305-9c1d-40fb-beee-76615ce58e32.png)
>>    *  POST후 반환되는 Response는 **Redirect를 두번 거치기 때문에** 반환되는 쿠키:cookie:는
>> **POST요청으로 받아온 세션쿠키**:cookie:가 아닌  **마지막 Redirect /login.php의 쿠키**:cookie:임.
>>    *  그러므로 body 또한 마지막 Redirect된 페이지의 body를 반환하기 떄문에 로그인 이전의 LMS 페이지 반환.
>  
> ## 해결방안 
> ###  1. Redirect를 못하도록 막고 반환되는 세션쿠키:cookie: 를 따로 저장, 
> ### 2. 세션쿠키:cookie: 를 전달해 데이터 크롤링.
>### 따라서 :one:세션쿠키를 얻는 과정과 :two:세션쿠키를 통해 크롤링하는 과정을 분리
<br>
<br>



# :one: 세션쿠키:cookie:를 얻는과정 <br>
> ## RequestOptions 설정 (Content-Type,followRedirects) 
>>### 1.  Content-Type
>>  dio에서 Reqeust시 Content-Type속성의 기본 값이 application/json 임. 따라서 application/x-www-form-urlencoded 로 설정해야함.  (참고 : https://jw910911.tistory.com/117) 
>>### 2.  followRedirects
>> Redirect 진행을 막기 위해 false로 설정
> ## 요청 URL 설정
>> ### URL : login/index.php
>> learn.hoseo.ac.kr/ 또는 /login.php로 설정할 경우 post 요청이 제대로 이루어지지 않음.
<br>
<br>

## 테스트용 전체 코드
<pre>   
import 'package:dio/dio.dart';

void main() async {
  final URL = Uri.parse("https://learn.hoseo.ac.kr/login/index.php");
  var dio = Dio();

  Map<String,String> data = {"username":"학번","password":"비밀번호"};
  Response r = await dio.postUri(URL,data: data,options: Options(
    contentType: 'application/x-www-form-urlencoded', 
    validateStatus: ((status) {return status!<500;}), //statusCode 오류제어
      followRedirects: false, //Redirect 방지
  ));

  print(r.headers);

}
</pre>
<br><br>
>## 결과 화면
>  ![image](https://user-images.githubusercontent.com/54611807/168313062-51e475f7-35cc-483b-82cf-43a9fb7f4359.png)
>> ### 정상적으로 세션 쿠키를 반환 :thumbsup::thumbsup:

<br>
<br>

# :two:세션쿠키:cookie:를 통해 크롤링하는 과정

> ## 헤더(header) 설정 
>> ### 세션쿠키:cookie:를 헤더에 포함하여 전송
> ## 요청 URL 설정
>> ### URL :learn.hoseo.ac.kr/ 
>> /login.php 또는 /login/index.php는 크롤링하려는 Url이 아님.

<br>
<br>

## 테스트용 코드
<pre>
import 'package:dio/dio.dart';


void main() async {
  final URL = Uri.parse("https://learn.hoseo.ac.kr/");
  var dio = Dio();
  Map<String,String> header = {"Cookie": "MoodleSession=세션쿠키값"};
    //dio.options.contentType = 'application/x-www-form-urlencoded';
     Response response2 = await dio.getUri(URL,options: Options(
        headers: header
     )
  );

 print(response2.data.contains('예정'));
}
</pre>
실행시 True 반환.

**Comment by ByteAurora** [comment]
확인했습니당

**Comment by Blenbre777** [comment]
오 뭐야 엄청 알록달록하게 잘 했잖아
