### ISSUE TITLE
2022.05.12 기능 및 UI 구성 회의

### ISSUE THREAD

**Issue by seo0jjjjj** [ILoveGameCoding/LMS-Reminder#2]
# 화면구성

>탭 공통
>  *사용자 정보 표시
>  * 환경설정 버튼

#  1번탭
>  * 미제출 과제 및 미시청 동영상 목록 표시 
>  *SQLite로 과제, 동영상 정보 저장 => 앱 실행 >시 LMS에서 불러온 데이터와 비교 후 제거 >애니메이션 추가
>  * 마감기한이 짧은 순으로 정렬
>  * 리스트뷰 아이템 구성 (과목명, 아이콘(과제, >동영상), 제목, 남은 시간)
>  * 리스트뷰 하단 스크롤 시 새로고침 기능
>  *리스트뷰 아이템 클릭 시 세부정보 다이얼로그 >표시
> * 과목명, 제목, 설명, 제출마감일자, >마감까지남은시간, LMS 연결 링크

# 2번탭
>- 제출마감(회색계열), 제출완료 했는데 기한 >남은 과제
>- 리스트뷰 아이템 클릭 시 세부정보 표시
>    - 과목명, 제목, 설명, 제출마감일자, >마감까지남은시간, LMS 연결 링크
>- 달력
>- 최근 날짜 기준 정렬

# 3번탭
>- 공지사항 목록 표시
>- 1순위. 미확인 공지사항 2순위. 최근 날짜 기준 >정렬
>- 확인 공지사항(회색계열), 미확인 >공지사항(NEW문구 표시)

# 설정탭
- 버전정보
- 알람
    - 마감 전 알림 시간(6시간, 1일, 3일 5일)
    - ~~notification 형식~~
- 미리보기
    - ~~과목명 보기~~
    - 과제, 동영상 제목 보기
- 로그아웃

**Comment by ByteAurora** [comment]
굳
