### ISSUE TITLE
LMS 항목 시간표기 

### ISSUE THREAD

**Issue by Blenbre777** [ILoveGameCoding/LMS-Reminder#3]
# LMS 항목 시간표기

<br>

## 문제
![image](https://user-images.githubusercontent.com/42365757/168651705-a15ada4d-03a6-4ea0-b644-200093d32ed1.png)
>현재 시간과 어플의 시간이 다르게 나옴

<br>

## 해결제시
휴대폰의 시간을 바꿔줘야 함 

1.좌측 상단 시간 두 번 클릭 <br>
![image](https://user-images.githubusercontent.com/42365757/168652526-cdb3d6db-a560-4ae9-9e5d-a00f6df6b6df.png)

2.우측 상단 메뉴바 - Settings <br>
![image](https://user-images.githubusercontent.com/42365757/168652670-c3b9e0bd-b6d2-4f7f-b8da-e98334faefb7.png)

3.Change date & time <br>
![image](https://user-images.githubusercontent.com/42365757/168652990-dd539956-d558-4508-9b5b-c8b187de9b2f.png)

4.체크 해제 후 Time zone 클릭 <br>
![image](https://user-images.githubusercontent.com/42365757/168653269-3c613334-ef74-49ba-aee2-327955b7b646.png)

5.Region - South Korea설정

## 해결
어플의 시간이 정상적으로 작동한다. <br>
![image](https://user-images.githubusercontent.com/42365757/168653775-24c076c4-4e47-4931-9a1b-31d27507381f.png)

**Comment by ByteAurora** [comment]
확인이용 나머지 인원도 확인하고 답글 달아주시면 이슈 닫겠습니다~

**Comment by seo0jjjjj** [comment]
굳
