### ISSUE TITLE
파일 다운로드를 위한 안드로이드 버전별 권한

### ISSUE THREAD

**Issue by ByteAurora** [ILoveGameCoding/LMS-Reminder#4]
# 파일 다운로드 문제
> - 어플 테스트 중 LMS 과제에 포함된 파일 다운로드 시 일부 기기에서 다운이 되지 않는 현상 확인<br>
> - 확인 결과 파일 다운로드 시 저장소와 관련된 권한이 필요<br><br><br>
>
> ## 저장소 접근 권한 부여
> ### Android Manifest
> <pre><code>&#60;uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
> &#60;uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
>
> &#60;!-- Android 11 이상(API Level 31)에서는 다음과 같은 권한이 추가로 필요 -->
> &#60;uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" /></code></pre>
>
> <br>
>
> ### pubspec.yaml
> - 실행 중 사용자에게 권한을 요청하기 위해 pub.dev의 [permission_handler](https://pub.dev/packages/permission_handler) 패키지 사용
> - 기기의 Android 버전을 확인하기 위해 pub.dev의 [device_info_plus](https://pub.dev/packages/device_info_plus) 패키지 사용
> <pre><code>dependencies:
>     permission_handler: ^9.2.0
>     device_info_plus: ^3.2.3</code></pre>
>
> <br>
>
> ### TabPageFinished, TabPageNotFinished에서 파일 다운로드 시 권한 요청
> <pre><code>
> // 저장소 접근 권한 요청
> await Permission.storage.request();
>  if (await Permission.storage.isDenied) {
>    // 해당 권한이 허용되지 않았을 경우 SnackBar로 권한 요청 알림
>    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
>      content: const Text('저장소 접근 권한이 필요합니다'),
>      duration: const Duration(seconds: 3),
>      action: SnackBarAction(
>          label: '설정',
>          onPressed: () {
>            // SnackBar 내 '설정' 터치 시 어플 설정화면으로 이동
>            openAppSettings();
>          }),
>    ));
>    return;
>  }
> </code></pre>
>
> <br>
>
> #### Android 11이상(API Level 30)에서는 아래와 같이 추가 권한 요청
> 
> <pre><code>
> if ((await DeviceInfoPlugin().androidInfo).version.sdkInt! >= 30) {
>     // 기기의 Android 버전이 30이상일 경우 - MANAGE_EXTERNAL_STORAGE 권한 요청
>     await Permission.manageExternalStorage.request();
> 
>     if (await Permission.manageExternalStorage.isDenied) {
>       // 해당 권한이 허용되지 않았을 경우 SnackBar로 권한 요청 알림
>       ScaffoldMessenger.of(context).showSnackBar(SnackBar(
>         content: const Text('저장소 관리 권한이 필요합니다'),
>         duration: const Duration(seconds: 3),
>         action: SnackBarAction(
>             label: '설정',
>             onPressed: () {
>               // SnackBar 내 '설정' 터치 시 어플 설정화면으로 이동
>               openAppSettings();
>             }),
>       ));
>       return;
>     }
>   }
> </code></pre>

<br><br>

# 결과
> - 현재 API Level 23 ~ 31까지 테스트 완료
> - 22 이하 버전의 경우 저장소 접근 경로가 달라 테스트 불가 (추후 구현)
> - S9+ (API Level 30)에서 '출처를 알 수 없는 앱 설치'에서 LMS 리마인더를 허용해줘야 파일 다운로드가 되는 경우가 있어, 최신버전의 LMS 리마인더 설치 후 다시 테스트해볼 예정 => @seo0jjjjj 가 테스트하고 Comment 남겨주세요

**Comment by Blenbre777** [comment]
어이쿠 ..

**Comment by seo0jjjjj** [comment]
<h2> 😢 안댐..ㅜ</h2>

추가권한을 주면되니까 안되는 갤s9+유저는 권한 설정 따로하는걸로..
